# -*- coding: utf-8 -*-
"""House Price Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cAtTLLLLrnDwR2cYzXACy2IkJJVDd5r
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("/content/House Price Data.csv")
df.head()

df.info()
df.describe()

df.isnull().sum()

df.shape

price_sqft = df['price_per_sqft']

# Mean ± Std Dev Method
mean = price_sqft.mean()
std = price_sqft.std()

lower = mean - 3*std
upper = mean + 3*std

df_mean = df[(price_sqft >= lower) & (price_sqft <= upper)]
df_mean.shape

# Percentile Method (5th–95th)
lower = price_sqft.quantile(0.05)
upper = price_sqft.quantile(0.95)

df_percentile = df[(price_sqft >= lower) & (price_sqft <= upper)]
df_percentile.shape

# IQR Method
Q1 = price_sqft.quantile(0.25)
Q3 = price_sqft.quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

df_iqr = df[(price_sqft >= lower) & (price_sqft <= upper)]
df_iqr.shape

# Z-Score Method
z = np.abs(stats.zscore(price_sqft))

df_z = df[z < 3]
df_z.shape

# Box Plot Comparison
plt.figure(figsize=(12,6))

datasets = [df, df_mean, df_percentile, df_iqr, df_z]
labels = ["Original","Mean-Std","Percentile","IQR","Z-Score"]

sns.boxplot(data=[d['price_per_sqft'] for d in datasets])
plt.xticks(range(len(labels)),labels)
plt.title("Outlier Removal Comparison")
plt.show()

# Normality Check & Transformation
sns.histplot(df_iqr['price_per_sqft'], kde=True)
plt.title("Before Transformation")
plt.show()

print("Skewness:", df_iqr['price_per_sqft'].skew())
print("Kurtosis:", df_iqr['price_per_sqft'].kurt())

df_iqr['log_price_sqft'] = np.log(df_iqr['price_per_sqft'])

sns.histplot(df_iqr['log_price_sqft'], kde=True)
plt.title("After Log Transformation")
plt.show()

print("Skewness:", df_iqr['log_price_sqft'].skew())
print("Kurtosis:", df_iqr['log_price_sqft'].kurt())

# Correlation + Heatmap
num_df = df_iqr.select_dtypes(include=['int64','float64'])

corr = num_df.corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

sns.scatterplot(data=df_iqr, x='total_sqft', y='price')
plt.title("Price vs Total Sqft")
plt.show()

sns.scatterplot(data=df_iqr, x='bath', y='price')
plt.title("Price vs Bathrooms")
plt.show()

sns.scatterplot(data=df_iqr, x='bhk', y='price')
plt.title("Price vs BHK")
plt.show()

"""Basic EDA showed that the price per square foot column contained strong positive skew
with several extreme outliers.

Outliers were detected using Mean–Std Dev, Percentile, IQR and Z-Score methods.
Among these, the IQR and Percentile methods gave the most reasonable results by
removing extreme anomalies while retaining useful values.

Box plot comparison confirmed that the IQR / Percentile filtered data appeared stable.

Normality testing showed that the data was right-skewed.
Log transformation reduced skewness and kurtosis, improving normal distribution.

Correlation and scatter plots showed relationships between price, size, and other
numerical variables.

Overall, the analysis improves data quality before applying ML models.

"""

